require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/api/**/*'
RSpec/DescribedClass:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
RSpec/ExampleLength:
  Max: 10
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Enabled: false
