language: ruby
rvm:
 - 2.4.0
 - 2.7.6
sudo: false
cache: bundler
install:
  - bundle install --path vendor/bundle
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
matrix:
  fast_finish: true
script:
  - bundle exec rubocop
  - bundle exec rspec
