version: '3.4'

services:
  app:
    image: cats_dealer:dev
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/cats_dealer
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54333:5432"

  redis:
    image: redis:6.0.5

  sidekiq:
    image: cats_dealer:dev
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/cats_dealer
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
