default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cats_dealer_development

test:
  <<: *default
  database: cats_dealer_test

production:
  <<: *default
  database: cats_dealer_production
