development: &development
  adapter: postgresql
  encoding: unicode
  database: cats_development
  pool: 5
  username: <%= ENV['LOCAL_DB_USER']%>
  password: <%= ENV['LOCAL_DB_PASSWORD']%>

test:
  <<: *development
  database: cats_test